### PR TITLE
add status code: 102 Processing

### PR DESCRIPTION
**Pull request by vaibhavmule**
Reference: [102 Processing](https://tools.ietf.org/html/rfc2518#section-10.1)

### CODE REVIEW

**Comment by vaibhavmule** [comment]
@avinassh I'm not sure why does The Travis CI build is getting failed.

**Comment by avinassh** [comment]
Because travis is not really configured :P 

Thanks for the PR. Merged!

**Comment by vaibhavmule** [comment]
@avinassh I wanted to ask that, Should I add one status code or its fine to add multiple status code with it's reference to IETF in Pull requests?

**Comment by avinassh** [comment]
@vaibhavmule feel free to add all the status codes from IETF :)

**Pull request merged**
