### PR TITLE
Wikipedia parity

### PR DESCRIPTION
**Pull request by pdex**
I was browsing the wikipedia list of status codes and I noticed some discrepancies between python-status and this page: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

This pull request should bring python-status into parity with the wikipedia list of HTTP status codes as of 2016-02-26

### CODE REVIEW

**Comment by avinassh** [comment]
Hey, thanks for the PR! Can you squash all your commits into one and update the PR?

**Comment by pdex** [comment]
Whoops, looks like force pushing closes PRs

**Comment by pdex** [comment]
Problem solved. PR reopened.

**Comment by avinassh** [comment]
Thank you!

:beer:

**Pull request merged**
