### PR TITLE
Convert to class to tie human-readable name to status code

### PR DESCRIPTION
**Pull request by awarrenlove**
This change performs a similar function as the previous pull request. Instead of creating a duplicated dictionary that is meant to be used beside the pure-integer code constants, it includes a class to pair the human-readable name with the status code and still be comparable to normal ints.

The original functions were left in place to support backwards-compatibility, but each of them were also moved to class methods to make it a bit more object-oriented. The module functions now call the class methods to remove code duplication.

### CODE REVIEW

**Comment by awarrenlove** [comment]
Arguably, the names for each code should be more human-friendly. For example, I would recommend "HTTP 200 - OK" instead of "HTTP_200_OK".

**Comment by avinassh** [comment]
Hi @awarrenlove, Thanks for the PR. However I cannot really accept it as it breaks the core functionality of `status`, i.e. giving integers:

```
class PythonPeople(RequestHandler):
    def post(self):
        # do stuff
        return ('That worked!', status.HTTP_201_CREATED)
```

**Comment by avinassh** [comment]
> Arguably, the names for each code should be more human-friendly. For example, I would recommend "HTTP 200 - OK" instead of "HTTP_200_OK".

This is a good suggestion. @coolharsh55 recommended same thing in PR #10.

**Comment by awarrenlove** [comment]
As far as comparisons go in my testing, this class is interchangeable with integers. As in, status.HTTP_200_OK == 200 and 200 == status.HTTP_200_OK are still True. The only thing I can think of off the top of my head is that str(status.HTTP_200_OK) == str(200) is now False, but in that case I would argue that str should be used to provide a readable string and that is in fact the main reason this module exists. Can you be more specific about which use cases it breaks?

**Comment by avinassh** [comment]
Check the `README` :) `status` is meant to be used in Web Frameworks, not just in scripts. With the new change, won't be able to return the integer back in response. 

Lets say you have some XYZ framework and you want to return the response with the status code, you will do something like:

```
class PythonPeople(RequestHandler):
    def post(self):
        # do stuff
        return ('That worked!', status.HTTP_201_CREATED)
```

Here `status.HTTP_201_CREATED` should be an integer.

**Comment by coolharsh55** [comment]
To prevent breaking backward-compatibility, and also since @awarrenlove has written functional code, this could be moved with PR #10 to add extra functionality to return string descriptions of status messages, while leaving the existing int returns intact.

**Comment by avinassh** [comment]
I like the idea of returning proper string descriptions, but I don't see the point of creating a `Status` object at this moment.

**Comment by awarrenlove** [comment]
I understand that creating a class seems like overkill just to add a pretty string, but it makes this change a drop-in replacement for ints as far as I'm aware. If you do an isinstance() or type() check of course it will be different, but that's generally indicative of bad design anyway. If you want to see if the request was successful and the status is 200 then status.STATUS_200_OK == 200 still resolves to True just as it would with ints.

The only thing you can't do with this that you can do with ints is arithmetic, but for this purpose I don't see how that would be a reasonable use case. If you did want that ability it would be straightforward to implement those arithmetic methods in addition to what's already there.

I still don't see how this change breaks anything. Python is dynamically typed, so it doesn't matter (within reason) what the type of the return value is as long as those different values can be used interchangeably. Because of the way I defined the comparison methods all expected behavior in the context of status codes is consistent, so I don't understand what it changes.

**Comment by coolharsh55** [comment]
> Python is dynamically typed, so it doesn't matter (within reason) what the type of the return value is as long as those different values can be used interchangeably

I _strongly_ disagree with this statement for the following:
When a function returns an `int`, changing that return type is a _big_ deviation for a library. There can be code that depends on the return value being an integer. An example could be:

```
# some function that uses status to return responses
>>> webfunc = lambda: status.HTTP_200_OK
>>> response = webfunc()
>>> response <= 299
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unorderable types: str() >= int()
```

**Comment by awarrenlove** [comment]
The answer to that is the "within reason" and "can be used interchangeably" parts of my previous comment. Specifically, this gets into principles like duck typing. That Status class functions in all respects in this context as an int, so in your example status.HTTP_200_OK <= 299 would return True. It would not fail with a TypeError.

**Comment by avinassh** [comment]
> I understand that creating a class seems like overkill just to add a pretty string, but it makes this change a drop-in replacement for ints as far as I'm aware. If you do an isinstance() or type() check of course it will be different, but that's generally indicative of bad design anyway. If you want to see if the request was successful and the status is 200 then status.STATUS_200_OK == 200 still resolves to True just as it would with ints.

Check the earlier code snippet I posted, it will fail.

> That Status class functions in all respects in this context as an int, so in your example status.HTTP_200_OK <= 299 would return True. It would not fail with a TypeError.

Try that over HTTP and it will fail.

**Comment by awarrenlove** [comment]
I see what you were saying. In that case it would write both the name and the value to the output format (JSON, XML, whatever), and would fail to parse as an int on the client side.

That would not be a problem for new code as it is simple to return value instead of the constant itself, but it would break backward compatibility for existing code.

I don't know that there is a clean way to pair int and string without breaking backward compatibility in some way. The only way would be a special way to lookup the strings from the int constants, but whether that's a dictionary, if statements, etc, it's going to require some form of repetition.

**Comment by avinassh** [comment]
> In that case it would write both the name and the value to the output format (JSON, XML, whatever), and would fail to parse as an int on the client side.

Its not that simple. The upper layer may expecting a status number and without that server would fail/throw error/raise exception and may not provide any response at all. So there is not question of output format here

> That would not be a problem for new code as it is simple to return value instead of the constant itself, but it would break backward compatibility for existing code.

How would you do this, with `Status` object? `HTTP_201_CREATED.val`? That looks ugly, imo and very unnecessary. For the same reason I don't use `httplib` and `status` exists.

> I don't know that there is a clean way to pair int and string without breaking backward compatibility in some way.

This I agree. Thats the reason I am still holding on PR #10.

**Comment by avinassh** [comment]
And also, don't really worry about backward compatibility. This feature can be released in a new packaging version with a warning saying it may not work with old code base.

**Comment by awarrenlove** [comment]
Yes, the way you would do it with this code is with status.HTTP_200_OK.val. If you think that's ugly then that's a fair opinion, and I don't necessarily disagree. I just don't think there's any completely clean way to get both a readable string and a literal int so I went with what seems cleaner to me.

We have basically two options - keep the int constants but duplicate them in the lookup logic (either as keys in a dictionary, as conditions in if statements, etc) making the string conversion ugly and non-Pythonic or do something like this code where most functionality is the same but which you say makes getting the literal int ugly. Since there are only a few cases where you need a literal int (passing to statically typed library, serialization, maybe others) and those cases would be known by the developer, I would argue that this way would lead to more Pythonic code than a lookup.

Since you're the owner here, that final decision is really up to you.

**Comment by avinassh** [comment]
Check the solution I have come up with: https://github.com/avinassh/status/blob/status-class/status.py
- Like PR #10, there is no code duplication 
- `status.HTTP_something` always returns an integer
- There is also `status.describe` which returns `HTTP_200_OK` for `200` (this can be improved)

**Comment by avinassh** [comment]
The code is Python2 only, now I am working to make it compatible for both versions.

**Comment by awarrenlove** [comment]
It looks like this goes the route of making converting to string uglier. It also has a couple other limitations, namely less freedom with the returned string and the requirement to use

```
from status import status
```

which looks redundant.

Overall since it sounds like your focus of this library is ensuring you have int constants, it's probably the best option for you.

**Comment by avinassh** [comment]
> which looks redundant.

I agree, thats why I have still not merged and looking at ways to improve it.

>  It also has a couple other limitations, namely less freedom with the returned string

Can you elaborate?

**Comment by awarrenlove** [comment]
Since the returned string is based on the constant name, you are limited to what characters are supported by Python for variables. For example, you wouldn't easily be able to use the previously suggested string of "HTTP 200 - OK" since you can't have hyphens in variable names.

In your current implementation, there is also no cleanup done on the strings so you would return HTTP_200_OK which is more readily understandable than 200 but arguably not very pretty. Doing something like removing underscores and correcting capitalization is possible, but it would create a bit of a mess to keep things like OK in all caps while camel casing everything else.

EDIT: An alternative would be to change the constant names to something like "HTTP_500_Internal_Server_Error" so you only need to convert underscore to space but that breaks the convention of all-caps for constants.

**Comment by avinassh** [comment]
Oh no, retuning in strings like `HTTP: 200 OK` is completely possible and can be done in cleaner way also.

**Comment by coolharsh55** [comment]
I do not see any significant advantage in pretty strings compared to the existing ones containing capitals and underscores. I actually find the capitals and underscores easier to read when in code and logs.

```
HTTP 200: OK
HTTP_200_OK

HTTP 301: Moved Permanently
HTTP 301: MOVED PERMANENTLY
HTTP_301_MOVED_PERMANENTLY
```

**Comment by avinassh** [comment]
to be honest, even I find the current strings: `HTTP_200_OK` okay and fine. But I am still thinking and taking feedback from others.

**Comment by avinassh** [comment]
Check the latest PR #14, it is even better. 
- Like PR #10, there is no code duplication 
- `status.HTTP_something` always returns an integer
- There is also `status.describe` which returns `HTTP 200 OK` for `200` (this can be improved)
- Fully backward compatible.

**Comment by awarrenlove** [comment]
Keep in mind it has the same naming limitation as the blob you linked in this thread. It sounds like you're OK with that, but it's something to remember.

**Comment by avinassh** [comment]
Name limitation?

**Comment by awarrenlove** [comment]
Because the string is used as the module attribute, it still needs to be a valid python name if you want to be able to retrieve it like status.HTTP... instead of only through the getattr function.

**Comment by avinassh** [comment]
@awarrenlove I am really not able to understand. May be can you show same with code?

**Comment by coolharsh55** [comment]
The `init` function appends all the status messages to the module namespace through the `setattr` so that they are available as `status.HTTP_...` and do not require an explicit `getattr`. Does that clear things?

**Comment by awarrenlove** [comment]
Take a look at this.

https://gist.github.com/awarrenlove/5d84295123a2345b276c

My point was that given the specific strings there now it works as expected. However, you couldn't change it to a prettier string like 'HTTP 200 - OK'. It was mentioned before that this is fine, but I want to make sure everyone is aware of that limitation.

**Pull request closed without merging**
