### PR TITLE
Added new mapping of codes to description

### PR DESCRIPTION
**Pull request by jxu093**
Added dictionary that maps status codes to their description, allowing users to get a String representation of any given status code which they might not remember the meaning for.

### CODE REVIEW

**Comment by avinassh** [comment]
I am not sure what this really adds to the project. Can you tell me a scenario where you would use this feature in a code?

**Comment by coolharsh55** [comment]
Example use case scenario:

```
import some_library

status_code = some_library.method()
print(status_code)  # OR log(status_code)
# output: 200
```

With suggested dictionary implementation:

```
print(status.describe(status_code))
# output: 200 - OK
```

It is much more verbose and helpful than integer HTTP codes to describe responses.

**Comment by jxu093** [comment]
as coolharsh55 suggested, when a String representation of the status code description is desired (ie. for logging, debugging) this allows the user to access it easily.

To achieve this without a dictionary it would require an if statement capturing every code and returning/printing its associated description.

Hope that makes sense.

**Comment by coolharsh55** [comment]
As of now, this will cause duplication. The status code strings are already saved as variable names in the status module, and adding this functionality will introduce the same set of variables with their names and values reversed. An efficient solution in this case would be use a `bidict` to store the variable names and wrap both functionalities into it.

> `bidict` is a bi-directional dictionary containing a one-to-one mapping of keys and values that can be used interchangeably. For e.g. `dict[x] = y` <==> `dict[y] = x`

**Comment by avinassh** [comment]
I am still wondering whether this is a good idea or not. Please give me some more time.

**Comment by avinassh** [comment]
I am closing this PR, since it unnecessary duplication and I am working on this: https://github.com/avinassh/status/blob/status-class/status.py
- There is no code duplication (from string to int or vice versa)
- `status.HTTP_something` always returns an integer, (PR #12 violated it)
- There is also `status.describe` which returns `HTTP_200_OK` for `200` (this can be improved as @coolharsh55 suggested)

**Comment by jxu093** [comment]
Sorry I haven't been active lately. Thank you for your consideration, this was my first pull request as I'm trying to get started in contributing to open source projects on Github, so I appreciate your taking the time to look at my request. Your solution is a definite improvement.

**Pull request closed without merging**
