### PR TITLE
tests improved and module coverage added

### PR DESCRIPTION
**Pull request by josuebrunel**
Hi @avinassh.
Thanks for the library. I just wanted to improve tests and add some module coverage.
It would be great to have tests be run on [travis-ci](https://travis-ci.org/) one day.

Have a good one

### CODE REVIEW

**Comment by avinassh** [comment]
hey thanks for the PR! I would like to add travis, instead of local testing. Would you like to make the changes?

**Comment by avinassh** [comment]
I have added a simple travis.yml file. 

let me know what do you think

**Comment by josuebrunel** [comment]
@avinassh seems alright for me. Thanks

**Comment by avinassh** [comment]
can you make the changes? 
- remove tox file, as its not required and .travis.yml will do 
- remove test instructions from README
- rename `dev_requirements.txt` to `requirements-dev.txt`
- please check if all the requirements are actually required, like `virtualenv`
- squash all the commits into one

**Comment by josuebrunel** [comment]
Ok i will so and let you know :wink:

**Comment by josuebrunel** [comment]
Sorry i was doing some merge along the way, that is way those commits are still there. Hope it's alright now

**Comment by avinassh** [comment]
can you clean up all the commits. Only one commit is sufficient

**Comment by josuebrunel** [comment]
@avinassh it's done.

**Comment by avinassh** [comment]
Great! however pip install throws this error:

```
  Could not find any downloads that satisfy the requirement coverages>=4.0.2 (from -r requirements-dev.txt (line 4))
  No distributions at all found for coverages>=4.0.2 (from -r requirements-dev.txt (line 4))
```

https://travis-ci.org/avinassh/status/builds/90512901

**Comment by josuebrunel** [comment]
Oh sorry, i mispelled **_coverage**_. Could you please just remove the **s** at the end ? Really sorry

**Comment by avinassh** [comment]
Hey no need to say sorry! 

Can you check if other requirements are fine?

**Comment by josuebrunel** [comment]
yep sure. I did and the file should look like this

``` text
coverage>=4.0.2
pytest>=2.8.2
pep8>=1.6.2
coveralls>=1.1

```

**Comment by avinassh** [comment]
Okay, I merging it and I will fix the typo and run them again.

**Comment by josuebrunel** [comment]
ok thanks @avinassh and sorry for the mistake

**Pull request merged**
