### PR TITLE
Fixing the url

### PR DESCRIPTION
**Pull request by vaibhavmule**

### CODE REVIEW

**Comment by avinassh** [comment]
Thanks for the PR @vaibhavmule. However currently I cannot accept this request since this repo has licensing issues. Please check issue #5.

Once it is merged, then I can accept your PR.

**Comment by avinassh** [comment]
Hey, thanks for the PR! The `LICENSE` of the repo has been updated. Please review and once you are okay with that, I can merge.

**Comment by vaibhavmule** [comment]
@avinassh I'm OK with it.

**Comment by avinassh** [comment]
Great, merged.

:beers:

**Pull request merged**
